const RAW_VOCAB = [
  { es: "el tren", de: "Zug", type: "Substantiv", irregular: false },
  { es: "el papel", de: "Papier; Pappe", type: "Substantiv", irregular: false },
  { es: "el tiempo", de: "Zeit; Wetter", type: "Substantiv", irregular: false },
  { es: "dentro de", de: "innerhalb (räumlich & zeitlich)", type: "Präposition", irregular: false },
  { es: "poder", de: "können", type: "Verb", irregular: true },
  { es: "el auto", de: "Auto", type: "Substantiv", irregular: false },
  { es: "lindo", de: "schön", type: "Adjektiv", irregular: false },
  { es: "en", de: "in (räumlich & zeitlich)", type: "Präposition", irregular: false },
  { es: "pero", de: "aber", type: "Konjunktion", irregular: false },
  { es: "caliente", de: "warm", type: "Adjektiv", irregular: false },
  { es: "poco", de: "wenig", type: "Adjektiv", irregular: false },
  { es: "demasiado (dinero)", de: "zu viel (Geld)", type: "Adjektiv", irregular: false },
  { es: "tomar", de: "trinken", type: "Verb", irregular: false },
  { es: "frio", de: "kalt", type: "Adjektiv", irregular: false },
  { es: "también", de: "auch", type: "Konjunktion", irregular: false },
  { es: "¿y que?", de: "na und?", type: "Redewendung", irregular: false },
  { es: "ahora (ya)", de: "jetzt (sofort)", type: "Adverb", irregular: false },
  { es: "sobre", de: "auf; über", type: "Präposition", irregular: false },
  { es: "grande", de: "groß", type: "Adjektiv", irregular: false },
  { es: "el che", de: "hey; Kumpel", type: "Substantiv", irregular: false },
  { es: "el pan", de: "Brot; Brötchen", type: "Substantiv", irregular: false },
  { es: "el vaso", de: "Glas", type: "Substantiv", irregular: false },
  { es: "feliz", de: "glücklich", type: "Adjektiv", irregular: false },
  { es: "comer", de: "essen", type: "Verb", irregular: false },
  { es: "o", de: "oder", type: "Konjunktion", irregular: false },
  { es: "la bolsa", de: "Tüte", type: "Substantiv", irregular: false },
  { es: "hablar", de: "sprechen", type: "Verb", irregular: false },
  { es: "llegar", de: "ankommen (an einem Ort)", type: "Verb", irregular: false },
  { es: "el perro", de: "Hund", type: "Substantiv", irregular: false },
  { es: "demasiado (caliente)", de: "zu (heiß)", type: "Adverb", irregular: false },
  { es: "pensar", de: "nachdenken", type: "Verb", irregular: true },
  { es: "y", de: "und", type: "Konjunktion", irregular: false },
  { es: "hacer", de: "tun; machen (Wetter: sein)", type: "Verb", irregular: true },
  { es: "decir", de: "sagen", type: "Verb", irregular: true },
  { es: "¿todo bien?", de: "alles klar?", type: "Redewendung", irregular: false },
  { es: "jugar", de: "spielen", type: "Verb", irregular: true },
  { es: "la comida", de: "Essen", type: "Substantiv", irregular: false },
  { es: "la calle", de: "Straße", type: "Substantiv", irregular: false },
  { es: "el mate", de: "Mate (Getränk, kulturell zentral)", type: "Substantiv", irregular: false },
  { es: "dar", de: "geben", type: "Verb", irregular: true },
  { es: "terminar", de: "beenden; kommen", type: "Verb", irregular: false },
  { es: "gustar", de: "gefallen", type: "Verb", irregular: true },
  { es: "posta", de: "wirklich; im Ernst", type: "Adverb", irregular: false },
  { es: "¿Qué onda?", de: "Was geht? / Wie läuft's?", type: "Redewendung", irregular: false },
  { es: "dormir", de: "schlafen", type: "Verb", irregular: true },
  { es: "la plata", de: "Geld (statt el dinero)", type: "Substantiv", irregular: false },
  { es: "ayer", de: "gestern", type: "Adverb", irregular: false },
  { es: "venir", de: "kommen", type: "Verb", irregular: true },
  { es: "ocupado", de: "beschäftigt", type: "Adjektiv", irregular: false },
  { es: "bárbaro", de: "super; klasse", type: "Adjektiv", irregular: false },
  { es: "mañana", de: "morgen", type: "Adverb", irregular: false },
  { es: "viste", de: "weißt du (Füllwort, sehr argentinisch)", type: "Redewendung", irregular: false },
  { es: "querer", de: "wollen", type: "Verb", irregular: true },
  { es: "ser", de: "sein (dauerhaft)", type: "Verb", irregular: true },
  { es: "el boliche", de: "Club; Disco", type: "Substantiv", irregular: false },
  { es: "necesitar", de: "brauchen", type: "Verb", irregular: false },
  { es: "mirar", de: "anschauen", type: "Verb", irregular: false },
  { es: "empezar", de: "anfangen", type: "Verb", irregular: true },
  { es: "ver", de: "sehen", type: "Verb", irregular: true },
  { es: "tener", de: "haben", type: "Verb", irregular: true },
  { es: "re (lindo)", de: "total/super (schön)", type: "Adverb", irregular: false },
  { es: "acá", de: "hier", type: "Adverb", irregular: false },
  { es: "mucho", de: "viel", type: "Adjektiv", irregular: false },
  { es: "el barrio", de: "Viertel; Stadtteil", type: "Substantiv", irregular: false },
  { es: "cansado", de: "müde", type: "Adjektiv", irregular: false },
  { es: "el pibe", de: "Junge/Mädchen", type: "Substantiv", irregular: false },
  { es: "vivir", de: "leben; wohnen", type: "Verb", irregular: false },
  { es: "ayudar", de: "helfen", type: "Verb", irregular: false },
  { es: "hoy", de: "heute", type: "Adverb", irregular: false },
  { es: "entender", de: "verstehen", type: "Verb", irregular: true },
  { es: "el boludo", de: "Trottel; auch freundschaftlich \"Alter\"", type: "Substantiv", irregular: false },
  { es: "ir", de: "gehen", type: "Verb", irregular: true },
  { es: "tranquilo", de: "ruhig; entspannt (auch \"alles gut\")", type: "Adjektiv", irregular: false },
  { es: "escuchar", de: "zuhören", type: "Verb", irregular: false },
  { es: "estar", de: "sein (temporär/Zustand)", type: "Verb", irregular: true },
  { es: "trabajar", de: "arbeiten", type: "Verb", irregular: false },
  { es: "la casa", de: "Haus", type: "Substantiv", irregular: false },
  { es: "copado", de: "cool; klasse", type: "Adjektiv", irregular: false },
  { es: "el amigo", de: "Freund/in", type: "Substantiv", irregular: false },
  { es: "el trabajo", de: "Arbeit", type: "Substantiv", irregular: false },
  { es: "saber", de: "wissen", type: "Verb", irregular: true },
  { es: "dejar", de: "lassen", type: "Verb", irregular: false },
  { es: "el finde", de: "Wochenende", type: "Substantiv", irregular: false },
  { es: "genial", de: "genial; toll", type: "Adjektiv", irregular: false },
  { es: "el celular", de: "Handy", type: "Substantiv", irregular: false },
  { es: "laburar", de: "arbeiten (Slang für 'trabajar')", type: "Verb", irregular: false },
  { es: "obvio", de: "klar; logisch", type: "Redewendung", irregular: false },
  { es: "contar", de: "erzählen", type: "Verb", irregular: true },
  { es: "boludear", de: "rumalbern; Zeit verschwenden", type: "Verb", irregular: false },
  { es: "de una", de: "klar, gerne! (Zusage)", type: "Redewendung", irregular: false },
  { es: "el laburo", de: "Arbeit (Slang für 'el trabajo')", type: "Substantiv", irregular: false },
  { es: "la palabra", de: "Wort", type: "Substantiv", irregular: false },
  { es: "claro", de: "klar; logisch (Zustimmung)", type: "Adjektiv", irregular: false },
  { es: "de donde", de: "woher?", type: "Redewendung", irregular: false },
  { es: "¿por qué?", de: "warum", type: "Redewendung", irregular: false },
  { es: "el viernes", de: "Freitag", type: "Substantiv", irregular: false },
  { es: "el hermano", de: "Bruder", type: "Substantiv", irregular: false },
  { es: "el día", de: "Tag", type: "Substantiv", irregular: false },
  { es: "malo", de: "schlecht", type: "Adjektiv", irregular: false },
  { es: "bueno", de: "gut", type: "Adjektiv", irregular: false },
  { es: "amarillo", de: "gelb", type: "Adjektiv", irregular: false },
  { es: "¡aguante!", de: "Zustimmungs-/Anfeuerungsruf (\"geht klar!\"/\"auf geht's!\")", type: "Redewendung", irregular: false },
  { es: "la birra", de: "Bier (Slang)", type: "Substantiv", irregular: false },
  { es: "el jueves", de: "Donnerstag", type: "Substantiv", irregular: false },
  { es: "¿cuándo?", de: "wann", type: "Adverb", irregular: false },
  { es: "la guita", de: "Geld (Slang)", type: "Substantiv", irregular: false },
  { es: "la hermana", de: "Schwester", type: "Substantiv", irregular: false },
  { es: "¿cómo?", de: "wie", type: "Adverb", irregular: false },
  { es: "la mesa", de: "Tisch", type: "Substantiv", irregular: false },
  { es: "el martes", de: "Dienstag", type: "Substantiv", irregular: false },
  { es: "el primo", de: "Cousin", type: "Substantiv", irregular: false },
  { es: "rojo", de: "rot", type: "Adjektiv", irregular: false },
  { es: "el abuelo", de: "Großvater", type: "Substantiv", irregular: false },
  { es: "rosa", de: "rosa", type: "Adjektiv", irregular: false },
  { es: "verde", de: "grün", type: "Adjektiv", irregular: false },
  { es: "el domingo", de: "Sonntag", type: "Substantiv", irregular: false },
  { es: "el lunes", de: "Montag", type: "Substantiv", irregular: false },
  { es: "el bondi", de: "Bus (Slang)", type: "Substantiv", irregular: false },
  { es: "gris", de: "grau", type: "Adjektiv", irregular: false },
  { es: "la abuela", de: "Großmutter", type: "Substantiv", irregular: false },
  { es: "viejo", de: "alt", type: "Adjektiv", irregular: false },
  { es: "¿quién?", de: "wer", type: "Adverb", irregular: false },
  { es: "marrón", de: "braun", type: "Adjektiv", irregular: false },
  { es: "negro", de: "schwarz", type: "Adjektiv", irregular: false },
  { es: "nuevo", de: "neu", type: "Adjektiv", irregular: false },
  { es: "azul", de: "blau", type: "Adjektiv", irregular: false },
  { es: "el padre", de: "Vater", type: "Substantiv", irregular: false },
  { es: "blanco", de: "weiß", type: "Adjektiv", irregular: false },
  { es: "el hijo", de: "Sohn", type: "Substantiv", irregular: false },
  { es: "la hija", de: "Tochter", type: "Substantiv", irregular: false },
  { es: "la familia", de: "Familie", type: "Substantiv", irregular: false },
  { es: "¿cuánto?", de: "wie viel", type: "Adverb", irregular: false },
  { es: "la mina", de: "Frau; Mädchen (Slang)", type: "Substantiv", irregular: false },
  { es: "la madre", de: "Mutter", type: "Substantiv", irregular: false },
  { es: "¿qué?", de: "was", type: "Adverb", irregular: false },
  { es: "el agua", de: "Wasser", type: "Substantiv", irregular: false },
  { es: "el libro", de: "Buch", type: "Substantiv", irregular: false },
  { es: "¿dónde?", de: "wo", type: "Adverb", irregular: false },
  { es: "el esposo", de: "Ehemann", type: "Substantiv", irregular: false },
  { es: "naranja", de: "orange", type: "Adjektiv", irregular: false },
  { es: "la noche", de: "Nacht", type: "Substantiv", irregular: false },
  { es: "el sábado", de: "Samstag", type: "Substantiv", irregular: false },
  { es: "el asado", de: "Grillfest; Gegrilltes", type: "Substantiv", irregular: false },
  { es: "el miércoles", de: "Mittwoch", type: "Substantiv", irregular: false },
  { es: "bailar", de: "tanzen", type: "Verb", irregular: false },
  { es: "si", de: "ob", type: "Konjunktion", irregular: false },
  { es: "la fiesta", de: "Party; Feier", type: "Substantiv", irregular: false },
  { es: "la tarde", de: "Nachmittag", type: "Substantiv", irregular: false },
  { es: "temprano", de: "früh", type: "Adverb", irregular: false },
  { es: "el novio / la novia", de: "Freund/in (Beziehung)", type: "Substantiv", irregular: false },
  { es: "la semana", de: "Woche", type: "Substantiv", irregular: false },
  { es: "comprar", de: "kaufen", type: "Verb", irregular: false },
  { es: "cocinar", de: "kochen", type: "Verb", irregular: false },
  { es: "rico", de: "lecker", type: "Adjektiv", irregular: false },
  { es: "el subte", de: "U-Bahn (Buenos Aires)", type: "Substantiv", irregular: false },
  { es: "caminar", de: "laufen; zu Fuß gehen", type: "Verb", irregular: false },
  { es: "último", de: "letzte", type: "Adjektiv", irregular: false },
  { es: "tener que", de: "müssen", type: "Verb", irregular: true },
  { es: "a", de: "nach; zu (Richtung)", type: "Präposition", irregular: false },
  { es: "próximo", de: "nächste", type: "Adjektiv", irregular: false },
];
