const RAW_VOCAB = [
  { ar: "el tren", de: "Zug", art: "Substantiv", irr: false },
  { ar: "el papel", de: "Papier; Pappe", art: "Substantiv", irr: false },
  { ar: "el tiempo", de: "Zeit; Wetter", art: "Substantiv", irr: false },
  { ar: "dentro de", de: "innerhalb (räumlich & zeitlich)", art: "Präposition", irr: false },
  { ar: "poder", de: "können", art: "Verb", irr: true },
  { ar: "el auto", de: "Auto", art: "Substantiv", irr: false },
  { ar: "lindo", de: "schön", art: "Adjektiv", irr: false },
  { ar: "en", de: "in (räumlich & zeitlich)", art: "Präposition", irr: false },
  { ar: "pero", de: "aber", art: "Konjunktion", irr: false },
  { ar: "caliente", de: "warm", art: "Adjektiv", irr: false },
  { ar: "poco", de: "wenig", art: "Adjektiv", irr: false },
  { ar: "demasiado (dinero)", de: "zu viel (Geld)", art: "Adjektiv", irr: false },
  { ar: "tomar", de: "trinken", art: "Verb", irr: false },
  { ar: "frio", de: "kalt", art: "Adjektiv", irr: false },
  { ar: "también", de: "auch", art: "Konjunktion", irr: false },
  { ar: "¿y que?", de: "na und?", art: "Redewendung", irr: false },
  { ar: "ahora (ya)", de: "jetzt (sofort)", art: "Adverb", irr: false },
  { ar: "sobre", de: "auf; über", art: "Präposition", irr: false },
  { ar: "grande", de: "groß", art: "Adjektiv", irr: false },
  { ar: "el che", de: "hey; Kumpel", art: "Substantiv", irr: false },
  { ar: "el pan", de: "Brot; Brötchen", art: "Substantiv", irr: false },
  { ar: "el vaso", de: "Glas", art: "Substantiv", irr: false },
  { ar: "feliz", de: "glücklich", art: "Adjektiv", irr: false },
  { ar: "comer", de: "essen", art: "Verb", irr: false },
  { ar: "o", de: "oder", art: "Konjunktion", irr: false },
  { ar: "la bolsa", de: "Tüte", art: "Substantiv", irr: false },
  { ar: "hablar", de: "sprechen", art: "Verb", irr: false },
  { ar: "llegar", de: "ankommen (an einem Ort)", art: "Verb", irr: false },
  { ar: "el perro", de: "Hund", art: "Substantiv", irr: false },
  { ar: "demasiado (caliente)", de: "zu (heiß)", art: "Adverb", irr: false },
  { ar: "pensar", de: "nachdenken", art: "Verb", irr: true },
  { ar: "y", de: "und", art: "Konjunktion", irr: false },
  { ar: "hacer", de: "tun; machen (Wetter: sein)", art: "Verb", irr: true },
  { ar: "decir", de: "sagen", art: "Verb", irr: true },
  { ar: "¿todo bien?", de: "alles klar?", art: "Redewendung", irr: false },
  { ar: "jugar", de: "spielen", art: "Verb", irr: true },
  { ar: "la comida", de: "Essen", art: "Substantiv", irr: false },
  { ar: "la calle", de: "Straße", art: "Substantiv", irr: false },
  { ar: "el mate", de: "Mate (Getränk, kulturell zentral)", art: "Substantiv", irr: false },
  { ar: "dar", de: "geben", art: "Verb", irr: true },
  { ar: "terminar", de: "beenden; kommen", art: "Verb", irr: false },
  { ar: "gustar", de: "gefallen", art: "Verb", irr: true },
  { ar: "posta", de: "wirklich; im Ernst", art: "Adverb", irr: false },
  { ar: "¿Qué onda?", de: "Was geht? / Wie läuft's?", art: "Redewendung", irr: false },
  { ar: "dormir", de: "schlafen", art: "Verb", irr: true },
  { ar: "la plata", de: "Geld (statt el dinero)", art: "Substantiv", irr: false },
  { ar: "ayer", de: "gestern", art: "Adverb", irr: false },
  { ar: "venir", de: "kommen", art: "Verb", irr: true },
  { ar: "ocupado", de: "beschäftigt", art: "Adjektiv", irr: false },
  { ar: "bárbaro", de: "super; klasse", art: "Adjektiv", irr: false },
  { ar: "mañana", de: "morgen", art: "Adverb", irr: false },
  { ar: "viste", de: "weißt du (Füllwort, sehr argentinisch)", art: "Redewendung", irr: false },
  { ar: "querer", de: "wollen", art: "Verb", irr: true },
  { ar: "ser", de: "sein (dauerhaft)", art: "Verb", irr: true },
  { ar: "el boliche", de: "Club; Disco", art: "Substantiv", irr: false },
  { ar: "necesitar", de: "brauchen", art: "Verb", irr: false },
  { ar: "mirar", de: "anschauen", art: "Verb", irr: false },
  { ar: "empezar", de: "anfangen", art: "Verb", irr: true },
  { ar: "ver", de: "sehen", art: "Verb", irr: true },
  { ar: "tener", de: "haben", art: "Verb", irr: true },
  { ar: "re (lindo)", de: "total/super (schön)", art: "Adverb", irr: false },
  { ar: "acá", de: "hier", art: "Adverb", irr: false },
  { ar: "mucho", de: "viel", art: "Adjektiv", irr: false },
  { ar: "el barrio", de: "Viertel; Stadtteil", art: "Substantiv", irr: false },
  { ar: "cansado", de: "müde", art: "Adjektiv", irr: false },
  { ar: "el pibe", de: "Junge/Mädchen", art: "Substantiv", irr: false },
  { ar: "vivir", de: "leben; wohnen", art: "Verb", irr: false },
  { ar: "ayudar", de: "helfen", art: "Verb", irr: false },
  { ar: "hoy", de: "heute", art: "Adverb", irr: false },
  { ar: "entender", de: "verstehen", art: "Verb", irr: true },
  { ar: "el boludo", de: "Trottel; auch freundschaftlich \"Alter\"", art: "Substantiv", irr: false },
  { ar: "ir", de: "gehen", art: "Verb", irr: true },
  { ar: "tranquilo", de: "ruhig; entspannt (auch \"alles gut\")", art: "Adjektiv", irr: false },
  { ar: "escuchar", de: "zuhören", art: "Verb", irr: false },
  { ar: "estar", de: "sein (temporär/Zustand)", art: "Verb", irr: true },
  { ar: "trabajar", de: "arbeiten", art: "Verb", irr: false },
  { ar: "la casa", de: "Haus", art: "Substantiv", irr: false },
  { ar: "copado", de: "cool; klasse", art: "Adjektiv", irr: false },
  { ar: "el amigo", de: "Freund/in", art: "Substantiv", irr: false },
  { ar: "el trabajo", de: "Arbeit", art: "Substantiv", irr: false },
  { ar: "saber", de: "wissen", art: "Verb", irr: true },
  { ar: "dejar", de: "lassen", art: "Verb", irr: false },
  { ar: "el finde", de: "Wochenende", art: "Substantiv", irr: false },
  { ar: "genial", de: "genial; toll", art: "Adjektiv", irr: false },
  { ar: "el celular", de: "Handy", art: "Substantiv", irr: false },
  { ar: "laburar", de: "arbeiten (Slang für 'trabajar')", art: "Verb", irr: false },
  { ar: "obvio", de: "klar; logisch", art: "Redewendung", irr: false },
  { ar: "contar", de: "erzählen", art: "Verb", irr: true },
  { ar: "boludear", de: "rumalbern; Zeit verschwenden", art: "Verb", irr: false },
  { ar: "de una", de: "klar, gerne! (Zusage)", art: "Redewendung", irr: false },
  { ar: "el laburo", de: "Arbeit (Slang für 'el trabajo')", art: "Substantiv", irr: false },
  { ar: "la palabra", de: "Wort", art: "Substantiv", irr: false },
  { ar: "claro", de: "klar; logisch (Zustimmung)", art: "Adjektiv", irr: false },
  { ar: "de donde", de: "woher?", art: "Redewendung", irr: false },
  { ar: "¿por qué?", de: "warum", art: "Redewendung", irr: false },
  { ar: "el viernes", de: "Freitag", art: "Substantiv", irr: false },
  { ar: "el hermano", de: "Bruder", art: "Substantiv", irr: false },
  { ar: "el día", de: "Tag", art: "Substantiv", irr: false },
  { ar: "malo", de: "schlecht", art: "Adjektiv", irr: false },
  { ar: "bueno", de: "gut", art: "Adjektiv", irr: false },
  { ar: "amarillo", de: "gelb", art: "Adjektiv", irr: false },
  { ar: "¡aguante!", de: "Zustimmungs-/Anfeuerungsruf (\"geht klar!\"/\"auf geht's!\")", art: "Redewendung", irr: false },
  { ar: "la birra", de: "Bier (Slang)", art: "Substantiv", irr: false },
  { ar: "el jueves", de: "Donnerstag", art: "Substantiv", irr: false },
  { ar: "¿cuándo?", de: "wann", art: "Adverb", irr: false },
  { ar: "la guita", de: "Geld (Slang)", art: "Substantiv", irr: false },
  { ar: "la hermana", de: "Schwester", art: "Substantiv", irr: false },
  { ar: "¿cómo?", de: "wie", art: "Adverb", irr: false },
  { ar: "la mesa", de: "Tisch", art: "Substantiv", irr: false },
  { ar: "el martes", de: "Dienstag", art: "Substantiv", irr: false },
  { ar: "el primo", de: "Cousin", art: "Substantiv", irr: false },
  { ar: "rojo", de: "rot", art: "Adjektiv", irr: false },
  { ar: "el abuelo", de: "Großvater", art: "Substantiv", irr: false },
  { ar: "rosa", de: "rosa", art: "Adjektiv", irr: false },
  { ar: "verde", de: "grün", art: "Adjektiv", irr: false },
  { ar: "el domingo", de: "Sonntag", art: "Substantiv", irr: false },
  { ar: "el lunes", de: "Montag", art: "Substantiv", irr: false },
  { ar: "el bondi", de: "Bus (Slang)", art: "Substantiv", irr: false },
  { ar: "gris", de: "grau", art: "Adjektiv", irr: false },
  { ar: "la abuela", de: "Großmutter", art: "Substantiv", irr: false },
  { ar: "viejo", de: "alt", art: "Adjektiv", irr: false },
  { ar: "¿quién?", de: "wer", art: "Adverb", irr: false },
  { ar: "marrón", de: "braun", art: "Adjektiv", irr: false },
  { ar: "negro", de: "schwarz", art: "Adjektiv", irr: false },
  { ar: "nuevo", de: "neu", art: "Adjektiv", irr: false },
  { ar: "azul", de: "blau", art: "Adjektiv", irr: false },
  { ar: "el padre", de: "Vater", art: "Substantiv", irr: false },
  { ar: "blanco", de: "weiß", art: "Adjektiv", irr: false },
  { ar: "el hijo", de: "Sohn", art: "Substantiv", irr: false },
  { ar: "la hija", de: "Tochter", art: "Substantiv", irr: false },
  { ar: "la familia", de: "Familie", art: "Substantiv", irr: false },
  { ar: "¿cuánto?", de: "wie viel", art: "Adverb", irr: false },
  { ar: "la mina", de: "Frau; Mädchen (Slang)", art: "Substantiv", irr: false },
  { ar: "la madre", de: "Mutter", art: "Substantiv", irr: false },
  { ar: "¿qué?", de: "was", art: "Adverb", irr: false },
  { ar: "el agua", de: "Wasser", art: "Substantiv", irr: false },
  { ar: "el libro", de: "Buch", art: "Substantiv", irr: false },
  { ar: "¿dónde?", de: "wo", art: "Adverb", irr: false },
  { ar: "el esposo", de: "Ehemann", art: "Substantiv", irr: false },
  { ar: "naranja", de: "orange", art: "Adjektiv", irr: false },
  { ar: "la noche", de: "Nacht", art: "Substantiv", irr: false },
  { ar: "el sábado", de: "Samstag", art: "Substantiv", irr: false },
  { ar: "el asado", de: "Grillfest; Gegrilltes", art: "Substantiv", irr: false },
  { ar: "el miércoles", de: "Mittwoch", art: "Substantiv", irr: false },
  { ar: "bailar", de: "tanzen", art: "Verb", irr: false },
  { ar: "si", de: "ob", art: "Konjunktion", irr: false },
  { ar: "la fiesta", de: "Party; Feier", art: "Substantiv", irr: false },
  { ar: "la tarde", de: "Nachmittag", art: "Substantiv", irr: false },
  { ar: "temprano", de: "früh", art: "Adverb", irr: false },
  { ar: "el novio / la novia", de: "Freund/in (Beziehung)", art: "Substantiv", irr: false },
  { ar: "la semana", de: "Woche", art: "Substantiv", irr: false },
  { ar: "comprar", de: "kaufen", art: "Verb", irr: false },
  { ar: "cocinar", de: "kochen", art: "Verb", irr: false },
  { ar: "rico", de: "lecker", art: "Adjektiv", irr: false },
  { ar: "el subte", de: "U-Bahn (Buenos Aires)", art: "Substantiv", irr: false },
  { ar: "caminar", de: "laufen; zu Fuß gehen", art: "Verb", irr: false },
  { ar: "último", de: "letzte", art: "Adjektiv", irr: false },
  { ar: "tener que", de: "müssen", art: "Verb", irr: true },
  { ar: "a", de: "nach; zu (Richtung)", art: "Präposition", irr: false },
  { ar: "próximo", de: "nächste", art: "Adjektiv", irr: false },
];
