// Vokabelliste für "Che, vamos a estudiar"
// Bei neuen Vokabeln: diese Datei einfach ersetzen, index.html bleibt unverändert.
const RAW_VOCAB = [
{ar:"el tren",de:"Zug",art:"Substantiv",irr:false,ex:null},
{ar:"el papel",de:"Papier; Pappe",art:"Substantiv",irr:false,ex:null},
{ar:"el tiempo",de:"Zeit; Wetter",art:"Substantiv",irr:false,ex:null},
{ar:"dentro de",de:"innerhalb (räumlich & zeitlich)",art:"Präposition",irr:false,ex:"dentro del coche\ndentro de un año"},
{ar:"poder",de:"können",art:"Verb",irr:true,ex:null},
{ar:"el auto",de:"Auto",art:"Substantiv",irr:false,ex:null},
{ar:"lindo",de:"schön",art:"Adjektiv",irr:false,ex:null},
{ar:"en",de:"in (räumlich & zeitlich)",art:"Präposition",irr:false,ex:null},
{ar:"pero",de:"aber",art:"Konjunktion",irr:false,ex:null},
{ar:"caliente",de:"warm",art:"Adjektiv",irr:false,ex:null},
{ar:"poco",de:"wenig",art:"Adjektiv",irr:false,ex:null},
{ar:"demasiado (dinero)",de:"zu viel (Geld)",art:"Adjektiv",irr:false,ex:null},
{ar:"tomar",de:"trinken",art:"Verb",irr:false,ex:null},
{ar:"frio",de:"kalt",art:"Adjektiv",irr:false,ex:null},
{ar:"también",de:"auch",art:"Konjunktion",irr:false,ex:null},
{ar:"¿y que?",de:"na und?",art:"Redewendung",irr:false,ex:null},
{ar:"ahora (ya)",de:"jetzt (sofort)",art:"Adverb",irr:false,ex:null},
{ar:"sobre",de:"auf; über",art:"Präposition",irr:false,ex:null},
{ar:"grande",de:"groß",art:"Adjektiv",irr:false,ex:null},
{ar:"el che",de:"hey; Kumpel",art:"Substantiv",irr:false,ex:null},
{ar:"el pan",de:"Brot; Brötchen",art:"Substantiv",irr:false,ex:null},
{ar:"el vaso",de:"Glas",art:"Substantiv",irr:false,ex:null},
{ar:"feliz",de:"glücklich",art:"Adjektiv",irr:false,ex:null},
{ar:"comer",de:"essen",art:"Verb",irr:false,ex:null},
{ar:"o",de:"oder",art:"Konjunktion",irr:false,ex:null},
{ar:"la bolsa",de:"Tüte",art:"Substantiv",irr:false,ex:null},
{ar:"hablar",de:"sprechen",art:"Verb",irr:false,ex:null},
{ar:"llegar",de:"ankommen (an einem Ort)",art:"Verb",irr:false,ex:null},
{ar:"el perro",de:"Hund",art:"Substantiv",irr:false,ex:null},
{ar:"demasiado (caliente)",de:"zu (heiß)",art:"Adverb",irr:false,ex:null},
{ar:"pensar",de:"nachdenken",art:"Verb",irr:true,ex:null},
{ar:"y",de:"und",art:"Konjunktion",irr:false,ex:null},
{ar:"hacer",de:"tun; machen (Wetter: sein)",art:"Verb",irr:true,ex:null},
{ar:"decir",de:"sagen",art:"Verb",irr:true,ex:null},
{ar:"¿todo bien?",de:"alles klar?",art:"Redewendung",irr:false,ex:null},
{ar:"jugar",de:"spielen",art:"Verb",irr:true,ex:null},
{ar:"la comida",de:"Essen",art:"Substantiv",irr:false,ex:null},
{ar:"la calle",de:"Straße",art:"Substantiv",irr:false,ex:null},
{ar:"el mate",de:"Mate (Getränk, kulturell zentral)",art:"Substantiv",irr:false,ex:null},
{ar:"dar",de:"geben",art:"Verb",irr:true,ex:null},
{ar:"terminar",de:"beenden; kommen",art:"Verb",irr:false,ex:null},
{ar:"gustar",de:"gefallen",art:"Verb",irr:true,ex:null},
{ar:"posta",de:"wirklich; im Ernst",art:"Adverb",irr:false,ex:null},
{ar:"¿Qué onda?",de:"Was geht? / Wie läuft's?",art:"Redewendung",irr:false,ex:null},
{ar:"dormir",de:"schlafen",art:"Verb",irr:true,ex:null},
{ar:"la plata",de:"Geld (statt el dinero)",art:"Substantiv",irr:false,ex:null},
{ar:"ayer",de:"gestern",art:"Adverb",irr:false,ex:null},
{ar:"venir",de:"kommen",art:"Verb",irr:true,ex:null},
{ar:"ocupado",de:"beschäftigt",art:"Adjektiv",irr:false,ex:null},
{ar:"bárbaro",de:"super; klasse",art:"Adjektiv",irr:false,ex:null},
{ar:"mañana",de:"morgen",art:"Adverb",irr:false,ex:null},
{ar:"viste",de:"weißt du (Füllwort, sehr argentinisch)",art:"Redewendung",irr:false,ex:null},
{ar:"querer",de:"wollen",art:"Verb",irr:true,ex:null},
{ar:"ser",de:"sein (dauerhaft)",art:"Verb",irr:true,ex:null},
{ar:"el boliche",de:"Club; Disco",art:"Substantiv",irr:false,ex:null},
{ar:"necesitar",de:"brauchen",art:"Verb",irr:false,ex:null},
{ar:"mirar",de:"anschauen",art:"Verb",irr:false,ex:null},
{ar:"empezar",de:"anfangen",art:"Verb",irr:true,ex:null},
{ar:"ver",de:"sehen",art:"Verb",irr:true,ex:null},
{ar:"tener",de:"haben",art:"Verb",irr:true,ex:null},
{ar:"re (lindo)",de:"total/super (schön)",art:"Adverb",irr:false,ex:null},
{ar:"acá",de:"hier",art:"Adverb",irr:false,ex:null},
{ar:"mucho",de:"viel",art:"Adjektiv",irr:false,ex:null},
{ar:"el barrio",de:"Viertel; Stadtteil",art:"Substantiv",irr:false,ex:null},
{ar:"cansado",de:"müde",art:"Adjektiv",irr:false,ex:null},
{ar:"el pibe",de:"Junge/Mädchen",art:"Substantiv",irr:false,ex:null},
{ar:"vivir",de:"leben; wohnen",art:"Verb",irr:false,ex:null},
{ar:"ayudar",de:"helfen",art:"Verb",irr:false,ex:null},
{ar:"hoy",de:"heute",art:"Adverb",irr:false,ex:null},
{ar:"entender",de:"verstehen",art:"Verb",irr:true,ex:null},
{ar:"el boludo",de:"Trottel; auch freundschaftlich \"Alter\"",art:"Substantiv",irr:false,ex:null},
{ar:"ir",de:"gehen",art:"Verb",irr:true,ex:null},
{ar:"tranquilo",de:"ruhig; entspannt (auch \"alles gut\")",art:"Adjektiv",irr:false,ex:null},
{ar:"escuchar",de:"zuhören",art:"Verb",irr:false,ex:null},
{ar:"estar",de:"sein (temporär/Zustand)",art:"Verb",irr:true,ex:null},
{ar:"trabajar",de:"arbeiten",art:"Verb",irr:false,ex:null},
{ar:"la casa",de:"Haus",art:"Substantiv",irr:false,ex:null},
{ar:"copado",de:"cool; klasse",art:"Adjektiv",irr:false,ex:null},
{ar:"el amigo",de:"Freund/in",art:"Substantiv",irr:false,ex:null},
{ar:"el trabajo",de:"Arbeit",art:"Substantiv",irr:false,ex:null},
{ar:"saber",de:"wissen",art:"Verb",irr:true,ex:null},
{ar:"dejar",de:"lassen",art:"Verb",irr:false,ex:"déjame pensar"},
{ar:"boludear",de:"rumalbern; Zeit verschwenden",art:"Verb",irr:false,ex:null},
{ar:"de una",de:"klar, gerne! (Zusage)",art:"Redewendung",irr:false,ex:null},
{ar:"el laburo",de:"Arbeit (Slang für 'el trabajo')",art:"Substantiv",irr:false,ex:null},
{ar:"el finde",de:"Wochenende",art:"Substantiv",irr:false,ex:null},
{ar:"genial",de:"genial; toll",art:"Adjektiv",irr:false,ex:null},
{ar:"el celular",de:"Handy",art:"Substantiv",irr:false,ex:null},
{ar:"laburar",de:"arbeiten (Slang für 'trabajar')",art:"Verb",irr:false,ex:null},
{ar:"obvio",de:"klar; logisch",art:"Redewendung",irr:false,ex:null},
{ar:"contar",de:"erzählen",art:"Verb",irr:true,ex:null},
{ar:"la birra",de:"Bier (Slang)",art:"Substantiv",irr:false,ex:null},
{ar:"la guita",de:"Geld (Slang)",art:"Substantiv",irr:false,ex:null},
{ar:"el bondi",de:"Bus (Slang)",art:"Substantiv",irr:false,ex:null},
{ar:"la mina",de:"Frau; Mädchen (Slang)",art:"Substantiv",irr:false,ex:null},
{ar:"el asado",de:"Grillfest; Gegrilltes",art:"Substantiv",irr:false,ex:null},
{ar:"¡aguante!",de:"Zustimmungs-/Anfeuerungsruf (\"geht klar!\"/\"auf geht's!\")",art:"Redewendung",irr:false,ex:null},
{ar:"la mesa",de:"Tisch",art:"Substantiv",irr:false,ex:null},
{ar:"viejo",de:"alt",art:"Adjektiv",irr:false,ex:null},
{ar:"nuevo",de:"neu",art:"Adjektiv",irr:false,ex:null},
{ar:"la familia",de:"Familie",art:"Substantiv",irr:false,ex:null},
{ar:"el agua",de:"Wasser",art:"Substantiv",irr:false,ex:null},
{ar:"el libro",de:"Buch",art:"Substantiv",irr:false,ex:null},
{ar:"la noche",de:"Nacht",art:"Substantiv",irr:false,ex:null},
{ar:"el día",de:"Tag",art:"Substantiv",irr:false,ex:null},
{ar:"malo",de:"schlecht",art:"Adjektiv",irr:false,ex:null},
{ar:"bueno",de:"gut",art:"Adjektiv",irr:false,ex:null},
{ar:"¿por qué?",de:"warum",art:"Redewendung",irr:false,ex:null},
{ar:"¿cuándo?",de:"wann",art:"Adverb",irr:false,ex:null},
{ar:"¿cómo?",de:"wie",art:"Adverb",irr:false,ex:null},
{ar:"¿quién?",de:"wer",art:"Adverb",irr:false,ex:null},
{ar:"¿cuánto?",de:"wie viel",art:"Adverb",irr:false,ex:null},
{ar:"¿qué?",de:"was",art:"Adverb",irr:false,ex:null},
{ar:"¿dónde?",de:"wo",art:"Adverb",irr:false,ex:null},
{ar:"verde",de:"grün",art:"Adjektiv",irr:false,ex:null},
{ar:"gris",de:"grau",art:"Adjektiv",irr:false,ex:null},
{ar:"marrón",de:"braun",art:"Adjektiv",irr:false,ex:null},
{ar:"negro",de:"schwarz",art:"Adjektiv",irr:false,ex:null},
{ar:"azul",de:"blau",art:"Adjektiv",irr:false,ex:null},
{ar:"blanco",de:"weiß",art:"Adjektiv",irr:false,ex:null},
{ar:"naranja",de:"orange",art:"Adjektiv",irr:false,ex:null},
{ar:"amarillo",de:"gelb",art:"Adjektiv",irr:false,ex:null},
{ar:"rojo",de:"rot",art:"Adjektiv",irr:false,ex:null},
{ar:"rosa",de:"rosa",art:"Adjektiv",irr:false,ex:null},
{ar:"el jueves",de:"Donnerstag",art:"Substantiv",irr:false,ex:null},
{ar:"el sábado",de:"Samstag",art:"Substantiv",irr:false,ex:null},
{ar:"el viernes",de:"Freitag",art:"Substantiv",irr:false,ex:null},
{ar:"el martes",de:"Dienstag",art:"Substantiv",irr:false,ex:null},
{ar:"el domingo",de:"Sonntag",art:"Substantiv",irr:false,ex:null},
{ar:"el lunes",de:"Montag",art:"Substantiv",irr:false,ex:null},
{ar:"el miércoles",de:"Mittwoch",art:"Substantiv",irr:false,ex:null},
{ar:"el abuelo",de:"Großvater",art:"Substantiv",irr:false,ex:null},
{ar:"la abuela",de:"Großmutter",art:"Substantiv",irr:false,ex:null},
{ar:"el padre",de:"Vater",art:"Substantiv",irr:false,ex:null},
{ar:"el hijo",de:"Sohn",art:"Substantiv",irr:false,ex:null},
{ar:"la hija",de:"Tochter",art:"Substantiv",irr:false,ex:null},
{ar:"la madre",de:"Mutter",art:"Substantiv",irr:false,ex:null},
{ar:"el esposo",de:"Ehemann",art:"Substantiv",irr:false,ex:null},
{ar:"el hermano",de:"Bruder",art:"Substantiv",irr:false,ex:null},
{ar:"la hermana",de:"Schwester",art:"Substantiv",irr:false,ex:null},
{ar:"el primo",de:"Cousin",art:"Substantiv",irr:false,ex:null},
{ar:"uno",de:"eins",art:"Adjektiv",irr:false,ex:null},
{ar:"dos",de:"zwei",art:"Adjektiv",irr:false,ex:null},
{ar:"tres",de:"drei",art:"Adjektiv",irr:false,ex:null},
];
